# Configuration file to predict.


# ----------data path----------
bert_model: data/bert/scibert_scivocab_cased

test_data: data/corpora/EPI/test/
output_dir: epi/epi-predict-test/ev-ann
model_path: data/models/epi/epi/model/
saved_params: data/models/epi/epi/epi.param

# eval
ev_eval_entities: [Entity]

# ----------setting----------
gpu: 0
batchsize: 16
seed: 42