# Configuration file to predict.


# ----------data path----------
bert_model: data/bert/scibert_scivocab_cased

test_data: data/corpora/GE11/test/
output_dir: ge11/ge11-predict-test/ev-ann
model_path: data/models/ge11/ge11/model/
saved_params: data/models/ge11/ge11/ge11.param

# eval
ev_eval_entities: [Entity]

# ----------setting----------
gpu: 0
batchsize: 16
seed: 42