# Configuration file to predict.


# ----------data path----------
bert_model: data/bert/scibert_scivocab_cased

test_data: data/corpora/GE13/test/
output_dir: ge13/ge13-predict-test/ev-ann
model_path: data/models/ge13/ge13/model/
saved_params: data/models/ge13/ge13/ge13.param

# eval
ev_eval_entities: [Entity,Anaphora]

# ----------setting----------
gpu: 0
batchsize: 16
seed: 42