# Configuration file to predict.


# ----------data path----------
bert_model: data/bert/scibert_scivocab_cased

test_data: data/corpora/ID11/dev/
output_dir: id/id-predict-dev/ev-ann
model_path: data/models/id/model/
saved_params: data/models/id/id.param

# eval
ev_eval_entities: [Entity]

# ----------setting----------
gpu: 0
batchsize: 16
seed: 42