# Configuration file to predict.


# ----------data path----------
# input & output dir
test_data: data/ID11/dev/
output_dir: id11-predict-dev/ev-ann

# model path
model_path: data/models/id11/model/
saved_params: data/models/id11/id11.param
bert_model: data/bert/scibert_scivocab_cased

# eval
ev_eval_entities: [Entity]

# ----------setting----------
gpu: 3
batchsize: 16
seed: 42