# Configuration file to predict.


# ----------data path----------
bert_model: data/bert/scibert_scivocab_cased

test_data: data/corpora/PC/test/
output_dir: pc/pc-predict-test/ev-ann
model_path: data/models/pc/model/
saved_params: data/models/pc/pc.param

# eval
ev_eval_entities: []

# ----------setting----------
gpu: 0
batchsize: 16
seed: 42